### PR TITLE
Improve Soundplorer double-click behavior and add auto-play toggle

### PR DESCRIPTION
**Pull request by henbagle**
Improved double click to play behavior in Soundplorer, as part of #225. Double clicking on an entry now correctly stops any previously playing entry and will start the new audio. Double clicking also now works on ISACT and AFC entries.

Also, ISACT entries will now show TLK strings where available, but the level-specific dialog files from ME1 will need to be loaded in TLKManager. Is there a better way to find a ME1 TLK string?
SoundplorerME1Tlk

### CODE REVIEW

**Comment by henbagle** [comment]
I was also working on a toggleable option to auto-play audio on selection (also from #225), but I wasn't sure if I should add the toggle to the global Properties.Settings object like the reverse endianness option, or just keep it local to Soundplorer.

**Comment by SirCxyrtyx** [comment]
Looks good! Thanks for contributing! 
In regards to the ME1 TLK strings, there really isn't a good way to find them unfortunately.

I wish I could tell you that there was a good reason why some of the tools (like Sequence Editor) store their settings in JSON files instead of Properties.Settings, but there isn't one. Using Properties.Settings is probably a better idea though. 

Our build pipeline is having some issues at the moment, so I'll wait for you to add the auto-play toggle to this PR, since I can't merge this right now anyway.

**Comment by henbagle** [comment]
I've added the toggle and fixed a few bugs. Will I need to merge in the latest Beta changes for this PR to pass the build?

**Comment by SirCxyrtyx** [comment]
Yes. If you can do that and it passes I'll merge.

**Pull request merged**
