### PR TITLE
PackageEd: Add experiment to add all PathNodes in a file to a BioSquadCombat

### PR DESCRIPTION
**Pull request by Exkywor**
Adds all the PathNodes in the file to the selected BioSquadCombat's AssignedPathnodes array.

### CODE REVIEW

**Comment by Mgamerz** [comment]
I think this should be in Pathfinding Editor, not Package Editor. This PR cannot be merged due to conflicts as well.

**Comment by vegz** [comment]
Pathfinding editor just refuses to open my file due to the amount of actors I have in. I think it would be better to be in Pathfinding editor but it refuses to work if your file has a ton of exports so having it in Package editor has been beneficial.

**Comment by Exkywor** [comment]
Hmm, if I could make a directory and file to have shared experiments code, I could have it in both. There is actually some code from my other experiments that could benefit from being moved to a shared file.

**Comment by Mgamerz** [comment]
> Pathfinding editor just refuses to open my file due to the amount of actors I have in. I think it would be better to be in Pathfinding editor but it refuses to work if your file has a ton of exports so having it in Package editor has been beneficial.

Do you have an example file that triggers this issue?

**Comment by vegz** [comment]
Turns out the file does open in Pathfinding editor, it only runs into issues if you have actors showing when you open the file. Though, I am not sure if its intended behavior to not work with that filter selected.

**Comment by Exkywor** [comment]
Well, if you can get it to work in the Pathfinding Editor, I'll move the experiment there. Though I still would like to add some file for shared experiments code later on.

**Comment by Exkywor** [comment]
I'm gonna close this PR, redo my code on a clean branch, and push, because the commit history of this branch looks like a mess right now.

**Pull request closed without merging**
