### PR TITLE
Fix Sequence Editor to handle SequenceReferences with imported references

### LINKED ISSUE #190: Sequence Editor fails to handle SequenceReference-s referencing imports
**Describe the bug**

Using Sequence Editor to open ME1 files which contain sequences with SequenceReference-s referencing imported sequences fails with a message box (see screenshot). 

**To Reproduce**

1. Open Sequence Editor
2. File > Open
3. Select a file with SequenceReference-s referencing imported sequences, e.g.:
   - `Mass Effect\BioGame\CookedPC\Packages\GameObjects\Sequences\BIOG_World_Q.upk`
   - `Mass Effect\BioGame\CookedPC\Packages\GameObjects\Sequences\BIOG_NormandyAirlock_Q.upk`
4. Click 'Open'

**Expected behavior**

Sequence Editor loads the sequences and otherwise works normally.

**Screenshots and files used to replicate this**

Error: image

**Version information:**

4.2 Debug, built from Beta branch 10/6/2020

**Stack trace**

N/A

**Other information**

After some investigation, I found out that the error happens because Sequence Editor does not expect referenced sequences to not be an export. Due to my limited knowledge of how Sequence Editor or UE works I'm not sure to what extent imported referenced sequences can be supported, but simply adding branches to handle sequence references with `oSequenceReference < 0` seems to do the trick and at least allow for everything else to be loaded and displayed. Not sure how correctly though.

Attaching a diff and a screenshot of a kinda-working SeqEd, if the changes I've made meet your approval I can open a PR.

<details>
<summary>Diff of proposed changes</summary>

```diff
diff --git a/ME3Explorer/Sequence Editor/SequenceEditorWPF.xaml.cs b/ME3Explorer/Sequence Editor/SequenceEditorWPF.xaml.cs
index 9bbc8a07..13eb2a95 100644
--- a/ME3Explorer/Sequence Editor/SequenceEditorWPF.xaml.cs	
+++ b/ME3Explorer/Sequence Editor/SequenceEditorWPF.xaml.cs	
@@ -404,8 +404,15 @@ namespace ME3Explorer.Sequence_Editor
 
                 if (SetProperty(ref _selectedItem, value) && value != null)
                 {
-                    value.IsSelected = true;
-                    LoadSequence((ExportEntry)value.Entry);
+                    if (value.Entry.UIndex > 0)
+                    {
+                        value.IsSelected = true;
+                        LoadSequence((ExportEntry)value.Entry);
+                    }
+                    else
+                    {
+                        MessageBox.Show("Can't select an imported sequence");
+                    }
                 }
             }
         }
@@ -435,7 +442,7 @@ namespace ME3Explorer.Sequence_Editor
                 {
                     LoadFile(d.FileName);
                 }
-                catch (Exception ex)
+                catch (Exception ex) when (!App.IsDebug)
                 {
                     MessageBox.Show(this, "Unable to open file:\n" + ex.Message);
                 }
@@ -484,7 +491,7 @@ namespace ME3Explorer.Sequence_Editor
                 variablesToolBox.Classes = SequenceObjectCreator.GetSequenceVariables(Pcc.Game).OrderBy(info => info.ClassName).ToList();
 
             }
-            catch (Exception ex)
+            catch (Exception ex) when (!App.IsDebug)
             {
                 MessageBox.Show(this, "Error:\n" + ex.Message);
                 Title = "Sequence Editor";
@@ -577,9 +584,22 @@ namespace ME3Explorer.Sequence_Editor
                         var propSequenceReference = exportEntry.GetProperty<ObjectProperty>("oSequenceReference");
                         if (propSequenceReference != null)
                         {
-                            TreeViewEntry t = FindSequences(pcc.GetUExport(propSequenceReference.Value));
-                            SequenceExports.Add(exportEntry);
-                            root.Sublinks.Add(t);
+                            if (propSequenceReference.Value > 0)
+                            {
+                                TreeViewEntry t = FindSequences(pcc.GetUExport(propSequenceReference.Value));
+                                SequenceExports.Add(exportEntry);
+                                root.Sublinks.Add(t);
+                            }
+                            else
+                            {
+                                // TODO: handle import
+                                var import = pcc.GetImport(propSequenceReference.Value);
+                                var importTreeViewEntry = new TreeViewEntry(import, $"#{import.UIndex}: {import.InstancedFullPath}")
+                                {
+                                    IsExpanded = false
+                                };
+                                root.Sublinks.Add(importTreeViewEntry);
+                            }
                         }
                     }
                 }
diff --git a/ME3Explorer/Sequence Editor/SequenceObjects.cs b/ME3Explorer/Sequence Editor/SequenceObjects.cs
index 7b63360e..5dd9d4f9 100644
--- a/ME3Explorer/Sequence Editor/SequenceObjects.cs	
+++ b/ME3Explorer/Sequence Editor/SequenceObjects.cs	
@@ -1569,7 +1569,15 @@ namespace ME3Explorer.SequenceObjects
                 var oSequenceReference = export.GetProperty<ObjectProperty>("oSequenceReference");
                 if (oSequenceReference != null)
                 {
-                    inputLinksProp = pcc.GetUExport(oSequenceReference.Value).GetProperty<ArrayProperty<StructProperty>>("InputLinks");
+                    if (oSequenceReference.Value > 0)
+                    {
+                        inputLinksProp = pcc.GetUExport(oSequenceReference.Value).GetProperty<ArrayProperty<StructProperty>>("InputLinks");
+                    }
+                    else
+                    {
+                        // TODO: handle import
+                        Debug.WriteLine($"Can't get input links of {export.InstancedFullPath} because it references an import.");
+                    }
                 }
             }
```

</details>

<details>
<summary>Screenshot of kinda-working SeqEd</summary>

image

</details>

### PR DESCRIPTION
**Pull request by 4rterius**

### CODE REVIEW

**Review by Mgamerz — APPROVED** [review]
Looks good. I'll merge this.

**Comment by Mgamerz** [comment]
I'll merge this once I get our build pipeline fixed up so it will properly check pull requests, since it immediately died on yours due to some fancy stuff we do to insert things at build time (that are not available to pull request branches it seems)

**Comment by 4rterius** [comment]
> I'll merge this once I get our build pipeline fixed up so it will properly check pull requests, since it immediately died on yours due to some fancy stuff we do to insert things at build time (that are not available to pull request branches it seems)

Yeah, I was wondering if I should report that it failed on PowerShell step, but then assumed that it was a known issue

**Comment by Mgamerz** [comment]
Merged. Thanks for fixing it. Let us know if you find anything else you'd like to help fix, we always are looking for more devs to help out.

**Pull request merged**
